### ISSUE TITLE
Open links in new tab on home page

### ISSUE THREAD

**Issue by alegemaate** [qjack001/qjack001.github.io#2]
I want to see everything but I keep losing focus
pls target="_blank"

**Comment by alegemaate** [comment]
For added security add in rel="noreferrer"

**Comment by qjack001** [comment]
That's not standard behaviour for links. Feel free to right-click -> open in new tab

**Comment by alegemaate** [comment]
Target was deprecated in the past, but as of html5 it has been reinstated. Because we now live in a tab-centric world, I personally do not think it is an issue to include them, specifically on external links. However, I did do some reading and realized that target does have a controversial history and companies are split on whether to include this behaviour. 🤔

**Comment by qjack001** [comment]
I think I will include it on external links once I implement actual project pages. That way they work normally, and only the outgoing links to github open in a new tab.

**Comment by qjack001** [comment]
Now relevant again with refactor. Will set `target="_blank"` on outgoing links, and keep the cards standard once I have the project pages up.
